# -*- coding: utf-8 -*-
"""Student performance task 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15b6fekoKAplkZskMjWKxJuOSyGh2nQLH
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("/content/drive/MyDrive/DV SKILL /StudentsPerformance.csv")

df.head()

df.tail()

df.info()

df.isnull()

cat={
    'gender',
    'race/ethnicity',
    'parental level of education',
    'lunch',
    'test preparation course'
}
for i in cat:
  df[i]=df[i].str.strip().str.lower()

for col in cat:
    print(col, ":", df[col].unique())

subjects = ['math score', 'reading score', 'writing score']

for subject in subjects:
    print("Mean:", df[subject].mean())
    print("Median:", df[subject].median())
    print("Standard Deviation:", df[subject].std())
    print("Q1:", df[subject].quantile(0.25))
    print("Q2:", df[subject].quantile(0.50))
    print("Q3:", df[subject].quantile(0.75))

