# -*- coding: utf-8 -*-
"""TASK 8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NoGduza5CHSDbyXF0haR2DteSduB1W6l
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/DV SKILL /Studentperformance_preprocessed.csv")

df.head()

plt.figure(figsize=(10,6))

sns.barplot(
    data=df,
    x="parental level of education",
    y="math score",
    hue="lunch"
)

plt.title("Average Math Score by Parental Education and Lunch Type")
plt.xlabel("Parental Education")
plt.ylabel("Average Math Score")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(8,6))

sns.boxplot(
    data=df,
    x="test preparation course",
    y="math score"
)

plt.title("Math Score Variance by Test Preparation")
plt.xlabel("Test Preparation Course")
plt.ylabel("Math Score")
plt.show()

plt.figure(figsize=(7,5))

sns.scatterplot(
    data=df,
    x="math score",
    y="reading score"
)

plt.title("Math Score vs Reading Score")
plt.xlabel("Math Score")
plt.ylabel("Reading Score")
plt.show()

plt.figure(figsize=(7,5))

sns.scatterplot(
    data=df,
    x="math score",
    y="writing score"
)

plt.title("Math Score vs Writing Score")
plt.xlabel("Math Score")
plt.ylabel("Writing Score")
plt.show()

corr = df[["math score", "reading score", "writing score"]].corr()

sns.heatmap(corr, annot=True)

plt.title("Correlation Heatmap")
plt.show()

print(corr)